# Generated by Django 4.1.7 on 2023-03-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("price", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
