# Generated by Django 4.1.7 on 2023-03-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_categoryitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="qunatity",
            new_name="quantity",
        ),
    ]
